/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Behandlungen: typeof import('./components/Behandlungen.vue')['default']
    FullScreenLoader: typeof import('./components/FullScreenLoader.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    Impressum: typeof import('./components/Impressum.vue')['default']
    ListDivider: typeof import('./components/ListDivider.vue')['default']
    MiniIconSheet: typeof import('./components/MiniIconSheet.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
